import os.path
import socket

class Config:
    def __init__(self):
        self.versionstring = 'v0.0'
        # from line which will be put on the report send 
        self.reportFrom = 'HUDORA Mail System <postmaster@hudora.de>'
        # enverlope sender for reports. Bounces will go there
        self.reportSender = 'postmaster@hudora.de'
        # basedir where we put our stuff
        self.bbboPath = '/Users/md/Desktop/code/bbbo'
        # the path where we can find our templates
        self.templatePath = os.path.join(self.bbboPath, 'templates')
        # our workspace
        self.workPath = os.path.join(self.bbboPath, 'work')        
        self.workUnpack = os.path.join(self.bbboPath, 'work')        
        self.quarantainePath = os.path.join(self.bbboPath, 'quarantaine')
        self.outqueuePath = os.path.join(self.bbboPath, 'outqueue')
        # this will be put on envery mail we send as a Mailheader
        self.fixedHeaders = 'X-Mailer: Black BamBoO %s' % self.versionstring
        # this will be put under every message we create
        self.fixedFooter = '-- \ngenerated by Black BamBoO %s' % self.versionstring
        #
        self.myFqdn = socket.getfqdn()
        self.smtpServer = 'gate.hudora.de'
        self.smtpDebugLevel = 0

        self.fixedHeaders.strip()
        

config = Config()
